openapi: 3.0.3
info:
  title: Bifrost Integrations - Workflow Engine API
  description: RESTful API for executing workflows and querying data providers
  version: 1.0.0
  contact:
    name: Bifrost Integrations Team

servers:
  - url: https://msp-automation-workflows.azurewebsites.net
    description: Production
  - url: http://localhost:7072
    description: Local development

security:
  - AzureAD: []

components:
  securitySchemes:
    AzureAD:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Azure AD JWT token

  parameters:
    XOrganizationId:
      name: X-Organization-Id
      in: header
      required: true
      description: Organization ID for org-scoped workflow execution
      schema:
        type: string
        format: uuid

  schemas:
    WorkflowMetadata:
      type: object
      required:
        - name
        - description
        - category
        - parameters
      properties:
        name:
          type: string
          description: Workflow identifier (function name)
        description:
          type: string
          description: Human-readable workflow description
        category:
          type: string
          description: Workflow category for organization
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowParameter'
        tags:
          type: array
          items:
            type: string
        version:
          type: string
          default: "1.0.0"

    WorkflowParameter:
      type: object
      required:
        - name
        - type
        - required
      properties:
        name:
          type: string
          description: Parameter name
        label:
          type: string
          description: Human-readable label for UI
        type:
          type: string
          enum: [string, int, bool, float, json, list]
          description: Parameter data type
        required:
          type: boolean
          description: Whether parameter is required
        defaultValue:
          description: Default value if not provided
        validation:
          type: object
          properties:
            pattern:
              type: string
              description: Regex pattern for string validation
            min:
              type: number
              description: Minimum value for numeric types
            max:
              type: number
              description: Maximum value for numeric types
            minLength:
              type: integer
              description: Minimum length for strings
            maxLength:
              type: integer
              description: Maximum length for strings
            enum:
              type: array
              items:
                type: string
              description: Allowed values
        dataProvider:
          type: string
          description: Data provider name for dynamic options
        helpText:
          type: string
          description: Additional help text for parameter

    DataProviderMetadata:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          description: Data provider identifier (function name)
        description:
          type: string
          description: Human-readable data provider description
        category:
          type: string
          description: Data provider category
        cacheTtlSeconds:
          type: integer
          description: Cache TTL in seconds (0 = no cache)
          default: 0
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/DataProviderParameter'
          description: Optional parameters for data provider

    DataProviderParameter:
      type: object
      required:
        - name
        - type
        - required
      properties:
        name:
          type: string
        type:
          type: string
          enum: [string, int, bool]
        required:
          type: boolean
        defaultValue:
          description: Default value

    MetadataResponse:
      type: object
      required:
        - workflows
        - dataProviders
      properties:
        workflows:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowMetadata'
        dataProviders:
          type: array
          items:
            $ref: '#/components/schemas/DataProviderMetadata'

    WorkflowExecutionRequest:
      type: object
      required:
        - parameters
      properties:
        parameters:
          type: object
          description: Key-value pairs matching workflow parameter definitions
          additionalProperties: true
        metadata:
          type: object
          properties:
            formId:
              type: string
              format: uuid
              description: Form ID if triggered via form submission
            executedBy:
              type: string
              description: User ID executing the workflow

    WorkflowExecutionResponse:
      type: object
      required:
        - executionId
        - status
        - startedAt
      properties:
        executionId:
          type: string
          format: uuid
          description: Unique execution ID (stored in WorkflowExecutions table)
        status:
          type: string
          enum: [Pending, Running, Success, Failed]
        result:
          type: object
          description: Workflow result data
          nullable: true
        errorMessage:
          type: string
          nullable: true
        durationMs:
          type: integer
          nullable: true
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true

    DataProviderResponse:
      type: object
      required:
        - options
      properties:
        options:
          type: array
          items:
            type: object
            required:
              - label
              - value
            properties:
              label:
                type: string
                description: Display label for UI
              value:
                description: Actual value to store (string, int, bool, object)
              metadata:
                type: object
                description: Additional metadata for option
        cached:
          type: boolean
          description: Whether response was cached
        cachedAt:
          type: string
          format: date-time
          description: Cache timestamp

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object

paths:
  # ==================== METADATA ====================
  /admin/metadata:
    get:
      summary: Get workflow and data provider metadata
      description: Returns all registered workflows and data providers with their parameter definitions
      tags: [Admin]
      security: []
      responses:
        '200':
          description: Metadata for all workflows and data providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataResponse'
              examples:
                example:
                  value:
                    workflows:
                      - name: user_onboarding
                        description: Onboard new M365 user with license assignment
                        category: user_management
                        parameters:
                          - name: first_name
                            label: First Name
                            type: string
                            required: true
                          - name: last_name
                            label: Last Name
                            type: string
                            required: true
                          - name: license
                            label: License Type
                            type: string
                            required: true
                            dataProvider: get_available_licenses
                        tags: [m365, user]
                    dataProviders:
                      - name: get_available_licenses
                        description: Returns available M365 licenses for organization
                        category: m365
                        cacheTtlSeconds: 300

  # ==================== WORKFLOWS ====================
  /workflows/{workflowName}:
    parameters:
      - name: workflowName
        in: path
        required: true
        description: Name of the workflow to execute
        schema:
          type: string
      - $ref: '#/components/parameters/XOrganizationId'

    post:
      summary: Execute a workflow
      description: Executes a workflow with provided parameters and organization context
      tags: [Workflows]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowExecutionRequest'
            examples:
              onboarding:
                summary: User onboarding example
                value:
                  parameters:
                    first_name: John
                    last_name: Doe
                    license: SPE_E5
                  metadata:
                    formId: 123e4567-e89b-12d3-a456-426614174000
                    executedBy: user@example.com
      responses:
        '200':
          description: Workflow execution completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowExecutionResponse'
        '202':
          description: Workflow execution started (async workflows)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowExecutionResponse'
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user lacks canExecuteWorkflows permission
        '404':
          description: Workflow not found
        '500':
          description: Workflow execution failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowExecutionResponse'

  # ==================== DATA PROVIDERS ====================
  /data-providers/{providerName}:
    parameters:
      - name: providerName
        in: path
        required: true
        description: Name of the data provider to execute
        schema:
          type: string
      - $ref: '#/components/parameters/XOrganizationId'

    get:
      summary: Get data provider options
      description: Executes a data provider and returns options for form field population
      tags: [Data Providers]
      parameters:
        - name: filterParam
          in: query
          description: Optional filter parameter (if data provider supports filtering)
          schema:
            type: string
      responses:
        '200':
          description: Data provider options
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProviderResponse'
              examples:
                licenses:
                  summary: Available M365 licenses
                  value:
                    options:
                      - label: Microsoft 365 E5
                        value: SPE_E5
                        metadata:
                          skuId: 06ebc4ee-1bb5-47dd-8120-11324bc54e06
                          available: 15
                      - label: Microsoft 365 E3
                        value: SPE_E3
                        metadata:
                          skuId: 05e9a617-0261-4cee-bb44-138d3ef5d965
                          available: 42
                    cached: true
                    cachedAt: "2025-10-10T14:32:00Z"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user lacks permissions
        '404':
          description: Data provider not found
        '500':
          description: Data provider execution failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

tags:
  - name: Admin
    description: Administrative endpoints for metadata discovery
  - name: Workflows
    description: Workflow execution endpoints
  - name: Data Providers
    description: Data provider execution endpoints for dynamic form fields
