"""
Bifrost contract models organized by domain.
"""

# Base utilities and helpers
from src.models.contracts.base import (
    DataProviderInputMode,
    IntegrationType,
    RetryPolicy,
    generate_entity_id,
)

from src.models.contracts.ai_models import (
    AIConnectionTestResponse,
    AIModelAssignmentKey,
    AIModelAssignmentResponse,
    AIModelAssignmentUpdate,
    AIModelProfileCreate,
    AIModelProfileMergeRequest,
    AIModelProfileMergeResponse,
    AIModelProfileResponse,
    AIModelProfileUpdate,
    AIModelsResponse,
    AIProviderConnectionCreate,
    AIProviderConnectionResponse,
    AIProviderConnectionSummary,
    AIProviderConnectionUpdate,
    AIProviderKind,
)

# Organizations
from src.models.contracts.organizations import (
    CreateOrganizationRequest,
    OrganizationBase,
    OrganizationCreate,
    OrganizationPublic,
    OrganizationUpdate,
    UpdateOrganizationRequest,
)

# Users & Roles
from src.models.contracts.users import (
    AssignAppsToRoleRequest,
    AssignFormsToRoleRequest,
    AssignKnowledgeToRoleRequest,
    AssignUsersToRoleRequest,
    AssignWorkflowsToRoleRequest,
    CreateRoleRequest,
    CreateUserRequest,
    GrantPermissionsRequest,
    KnowledgeAssignmentInput,
    PermissionsData,
    RoleAppsResponse,
    RoleBase,
    RoleConsumerCounts,
    RoleCreate,
    RoleFormsResponse,
    RoleKnowledgeEntry,
    RoleKnowledgeResponse,
    RolePublic,
    RoleUpdate,
    RoleUserSummary,
    RoleUsersResponse,
    RoleWorkflowsResponse,
    UnassignAgentsFromRoleRequest,
    UnassignAppsFromRoleRequest,
    UnassignFormsFromRoleRequest,
    UnassignKnowledgeFromRoleRequest,
    UnassignUsersFromRoleRequest,
    UnassignWorkflowsFromRoleRequest,
    UpdateRoleRequest,
    BulkUserFailure,
    BulkUserOperation,
    BulkUserResponse,
    UpdateUserRequest,
    UserBase,
    UserCreate,
    UserFormsResponse,
    UserPermission,
    UserPublic,
    UserResponse,
    UserRolesResponse,
    UserUpdate,
)

# Authentication & MFA
from src.models.contracts.auth import (
    AuthStatusResponse,
    DeviceAuthorizeRequest,
    DeviceCodeResponse,
    DeviceTokenErrorResponse,
    DeviceTokenRequest,
    DeviceTokenResponse,
    LoginResponse,
    MFAEnrollVerifyRequest,
    MFAEnrollVerifyResponse,
    MFARequiredResponse,
    MFASetupRequiredResponse,
    MFASetupResponse,
    MFASetupTokenRequest,
    MFAVerifyRequest,
    OAuthLoginRequest,
    OAuthProviderInfo,
    TokenRefresh,
)

# Passkeys/WebAuthn
from src.models.contracts.passkeys import (
    PasskeyAuthOptionsRequest,
    PasskeyAuthOptionsResponse,
    PasskeyAuthVerifyRequest,
    PasskeyDeleteResponse,
    PasskeyListResponse,
    PasskeyPublic,
    PasskeyRegistrationOptionsRequest,
    PasskeyRegistrationOptionsResponse,
    PasskeyRegistrationVerifyRequest,
    PasskeyRegistrationVerifyResponse,
)

# Forms
from src.models.contracts.forms import (
    CreateFormRequest,
    DataProviderInputConfig,
    FormCaptchaChallenge,
    FormCreate,
    FormConfirmationResponse,
    FormExecutionResponse,
    FormFieldOptionsRequest,
    FormFieldOptionsResponse,
    FormFieldValidation,
    FormPublicationPublic,
    FormPublicationReview,
    FormPublicationUpdate,
    FormPublic,
    FormRuntimeDefinition,
    FormSchema,
    FormSubmissionRequest,
    FormSubmissionResponse,
    FormStartupResponse,
    FormUpdate,
    UpdateFormRequest,
)

# Applications (App Builder)
from src.models.contracts.applications import (
    AppFileCreate,
    AppFileListResponse,
    AppFileResponse,
    AppFileUpdate,
    ApplicationCreate,
    ApplicationDefinition,
    ApplicationDraftSave,
    ApplicationListResponse,
    ApplicationPublic,
    ApplicationPublishRequest,
    ApplicationRollbackRequest,
    ApplicationUpdate,
    VersionHistoryEntry,
    VersionHistoryResponse,
)

# Durable scheduler-owned platform jobs
from src.models.contracts.platform_jobs import (
    PlatformJobAccepted,
    PlatformJobCancelResponse,
    PlatformJobError,
    PlatformJobListResponse,
    PlatformJobProgress,
    PlatformJobPublic,
    PlatformJobStatus,
)
from src.models.contracts.scheduler_diagnostics import (
    SchedulerCapacityStatus,
    SchedulerDiagnosticsResponse,
    SchedulerLeaderStatus,
    SchedulerReplicaStatus,
    SchedulerTaskRunStatus,
    SchedulerTaskStatus,
    SystemDiagnosticLogPublic,
)

# Agents & Chat
from src.models.contracts.agents import (
    AgentCreate,
    AgentPublic,
    AgentSummary,
    AgentUpdate,
    AssignAgentsToRoleRequest,
    ChatRequest,
    ChatResponse,
    ChatStreamChunk,
    ConversationCreate,
    ConversationPublic,
    ConversationSummary,
    MessagePublic,
    RoleAgentsResponse,
    ToolCall,
    ToolResult,
)

# Audit log
from src.models.contracts.audit import (
    AuditLogActor,
    AuditLogEntry,
    AuditLogListResponse,
)

# Executions & Logs
from src.models.contracts.executions import (
    AIUsagePublicSimple,
    AIUsageTotalsSimple,
    CleanupTriggeredResponse,
    ExecutionBase,
    ExecutionCreate,
    ExecutionLogPublic,
    ExecutionPublic,
    ExecutionUpdate,
    ExecutionsListResponse,
    StuckExecutionsResponse,
    WorkflowExecution,
    WorkflowExecutionRequest,
    WorkflowExecutionResponse,
)

# Configuration & Secrets
from src.models.contracts.config import (
    ConfigBase,
    ConfigCreate,
    ConfigPublic,
    ConfigResponse,
    ConfigUpdate,
    IntegrationConfig,
    SecretBase,
    SecretCreate,
    SecretCreateRequest,
    SecretListResponse,
    SecretPublic,
    SecretResponse,
    SecretUpdate,
    SecretUpdateRequest,
    SetConfigRequest,
    SetIntegrationConfigRequest,
    UpdateConfigRequest,
)

# OAuth Connections
from src.models.contracts.oauth import (
    CreateOAuthConnectionRequest,
    EntityIdPickerCandidate,
    OAuthCallbackRequest,
    OAuthCallbackResponse,
    OAuthConnection,
    OAuthConnectionDetail,
    OAuthConnectionSummary,
    OAuthCredentials,
    OAuthCredentialsModel,
    OAuthCredentialsResponse,
    OAuthFlowType,
    OAuthProviderBase,
    OAuthProviderCreate,
    OAuthProviderPublic,
    OAuthProviderUpdate,
    OAuthStatus,
    UpdateOAuthConnectionRequest,
)

# Workflows & Metadata
from src.models.contracts.workflows import (
    AssignRolesToWorkflowRequest,
    DataProviderMetadata,
    FormDiscoveryMetadata,
    MetadataResponse,
    RegisterWorkflowRequest,
    RegisterWorkflowResponse,
    ValidationIssue,
    WorkflowKey,
    WorkflowKeyCreateRequest,
    WorkflowKeyResponse,
    WorkflowMetadata,
    WorkflowParameter,
    WorkflowRolesResponse,
    WorkflowUpdateRequest,
    WorkflowValidationRequest,
    WorkflowValidationResponse,
    EntityUsage,
    WorkflowUsageStats,
    DeleteWorkflowRequest,
)

# Data Providers
from src.models.contracts.data_providers import (
    DataProviderOption,
    DataProviderRequest,
    DataProviderResponse,
)

# Dashboard & Metrics
from src.models.contracts.dashboard import (
    DailyMetricsEntry,
    DailyMetricsResponse,
    DashboardMetricsResponse,
    ExecutionTimeSeriesBucket,
    ExecutionTimeSeriesResponse,
    ROISnapshot,
    ExecutionStats,
    OrganizationMetricsResponse,
    OrganizationMetricsSummary,
    PlatformMetricsResponse,
    RecentFailure,
    ResourceMetricsEntry,
    ResourceMetricsResponse,
    WorkflowMetricsResponse,
    WorkflowMetricsSummary,
)

# Health
from src.models.contracts.health import (
    BasicHealthResponse,
    GeneralHealthResponse,
    HealthCheck,
)

# Editor & Code
from src.models.contracts.editor import (
    AffectedEntity,
    AvailableReplacement,
    FileConflictResponse,
    FileContentRequest,
    FileContentResponse,
    FileDiagnostic,
    FileMetadata,
    FileType,
    FileStatResponse,
    PendingDeactivation,
    ScriptExecutionRequest,
    ScriptExecutionResponse,
    SearchRequest,
    SearchResponse,
    SearchResult,
    WorkflowDeactivationConflict,
    WorkflowIdConflict,
)

# File Operations (CLI push/pull)
from src.models.contracts.files import (
    FilePullRequest,
    FilePullResponse,
    WatchSessionRequest,
)

# Common models
from src.models.contracts.common import (
    BrandingSettings,
    BrandingTerm,
    BrandingTerminology,
    BrandingUpdateRequest,
    ErrorResponse,
    FileUploadRequest,
    FileUploadResponse,
    InstallPackageRequest,
    InstalledPackage,
    InstalledPackagesResponse,
    PackageInstallResponse,
    PackageUpdate,
    PackageUpdatesResponse,
    UploadedFileMetadata,
)

# Scheduling & Async Execution
from src.models.contracts.scheduling import (
    AsyncExecution,
    AsyncExecutionStatus,
    CronValidationRequest,
    CronValidationResponse,
)

# GitHub Integration
from src.models.contracts.github import (
    CommitAndPushRequest,
    CommitAndPushResponse,
    CommitHistoryResponse,
    CommitInfo,
    CompatibleReplacement,
    CompatibleReplacementsResponse,
    ConflictInfo,
    CreateRepoRequest,
    CreateRepoResponse,
    DeactivateWorkflowResponse,
    DetectedRepoInfo,
    FetchFromGitHubResponse,
    FileChange,
    GitFileStatus,
    GitHubBranchInfo,
    GitHubBranchesResponse,
    GitHubConfigEntity,
    GitHubConfigRequest,
    GitHubConfigResponse,
    GitHubRepoInfo,
    GitHubReposResponse,
    GitHubSetupResponse,
    GitRefreshStatusResponse,
    OrphanedWorkflowInfo,
    OrphanedWorkflowsResponse,
    OrphanInfo,
    PreflightIssue,
    PreflightResult,
    RecreateFileResponse,
    RemapWorkflowRequest,
    RemapWorkflowResponse,
    ReplaceWorkflowRequest,
    ReplaceWorkflowResponse,
    ValidateTokenRequest,
    WorkflowReference,
    WorkspaceAnalysisResponse,
    GitJobResponse,
    GitOpRequest,
    SyncRequest,
    CommitRequest,
    ResolveRequest,
    DiffRequest,
    DiscardRequest,
    DiscardResult,
    ConfirmDeletionsRequest,
    ConfirmDeletionsResult,
    ChangedFile,
    MergeConflict,
    FetchResult,
    WorkingTreeStatus,
    CommitResult,
    PullResult,
    PushResult,
    RepoStatusResponse,
    ResolveResult,
    SyncResult,
    AbortMergeResult,
    DiffResult,
    SyncExecuteRequest,
)

# CLI Models
from src.models.contracts.cli import (
    CLIConfigDeleteRequest,
    CLIConfigGetRequest,
    CLIConfigListRequest,
    CLIConfigSetRequest,
    CLIConfigValue,
    CLIFileDeleteRequest,
    CLIFileListRequest,
    CLIFileReadRequest,
    CLIFileWriteRequest,
    CLIRegisteredWorkflow,
    CLISessionContinueRequest,
    CLISessionContinueResponse,
    CLISessionExecutionSummary,
    CLISessionListResponse,
    CLISessionLogRequest,
    CLISessionPendingResponse,
    CLISessionRegisterRequest,
    CLISessionResponse,
    CLISessionResultRequest,
)

# SDK Response Models (for bifrost.* module returns)
from src.models.contracts.sdk import (
    ConfigData,
    IntegrationData,
    OAuthCredentials as SDKOAuthCredentials,
)

# Profile
from src.models.contracts.profile import (
    PasswordChange,
    ProfileResponse,
    ProfileUpdate,
)

# Memory
from src.models.contracts.memory import (
    MemoryDeleteResponse,
    MemoryEntryList,
    MemoryEntryPublic,
    MemoryPlatformSettings,
    MemoryPlatformSettingsUpdate,
    MemorySaveRequest,
    MemorySearchRequest,
    MemorySearchResponse,
    MemorySearchResult,
    MemoryUserSettings,
    MemoryUserSettingsUpdate,
)
from src.models.contracts.required_instructions import (
    RequiredInstructionsResponse,
    RequiredInstructionsSettings,
)

# Notifications
from src.models.contracts.notifications import (
    JobDispatchResponse,
    NotificationCategory,
    NotificationCreate,
    NotificationListResponse,
    NotificationPublic,
    NotificationStatus,
    NotificationUpdate,
    UploadLockInfo,
)

# External MCP client (server template + per-org connection + tool catalog)
from src.models.contracts.external_mcp import (
    MCPServerCreate,
    MCPServerUpdate,
    MCPServerSummary,
    MCPServerPublic,
    MCPConnectionCreate,
    MCPConnectionUpdate,
    MCPConnectionSummary,
    MCPConnectionPublic,
    MCPConnectionToolCreate,
    MCPConnectionToolUpdate,
    MCPConnectionToolPublic,
    UserMCPCredentialCreate,
    UserMCPCredentialPublic,
)

# Integrations
from src.models.contracts.integrations import (
    ConfigSchemaItem,
    ConfigItemType,
    IntegrationCreate,
    IntegrationUpdate,
    IntegrationResponse,
    IntegrationDetailResponse,
    IntegrationListResponse,
    IntegrationMappingCreate,
    IntegrationMappingUpdate,
    IntegrationMappingBatchItem,
    IntegrationMappingBatchRequest,
    IntegrationMappingBatchResponse,
    IntegrationMappingResponse,
    IntegrationMappingListResponse,
    EntityIdSourceUpdateRequest,
    MappingAuthorizeRequest,
    MappingAuthorizeResponse,
    OAuthConfigSummary,
    IntegrationTestRequest,
    IntegrationTestResponse,
)

# Decorator Properties
from src.models.contracts.decorators import (
    DecoratorInfo,
    DecoratorPropertiesResponse,
    DecoratorType,
    UpdatePropertiesRequest,
    UpdatePropertiesResponse,
)

# Maintenance
from src.models.contracts.maintenance import (
    CleanupOrphanedResponse,
    DocsIndexResponse,
    MaintenanceStatus,
    OrphanedEntity,
    PreflightIssueResponse,
    PreflightResponse,
    ReimportJobResponse,
)

# ROI
from src.models.contracts.roi import (
    ROISettingsRequest,
    ROISettingsResponse,
    ROISummaryResponse,
    WorkflowROIEntry,
    ROIByWorkflowResponse,
    OrganizationROIEntry,
    ROIByOrganizationResponse,
    ROITrendEntry,
    ROITrendsResponse,
)

# AI Usage
from src.models.contracts.ai_usage import (
    AIModelPricingBase,
    AIModelPricingCreate,
    AIModelPricingUpdate,
    AIModelPricingPublic,
    AIModelPricingListItem,
    AIModelPricingListResponse,
    AIUsageBase,
    AIUsagePublic,
    AIUsageTotals,
    AIUsageByModel,
    AIUsageSummaryResponse,
    UsageReportSummary,
    UsageTrend,
    WorkflowUsage,
    ConversationUsage,
    AgentUsage,
    OrganizationUsage,
    KnowledgeStorageUsage,
    KnowledgeStorageTrend,
    UsageReportResponse,
)

# Export/Import
from src.models.contracts.export_import import (
    BulkExportRequest,
    ConfigExportFile,
    ExportMetadata,
    ImportResult,
    ImportResultItem,
    IntegrationExportFile,
    KnowledgeExportFile,
    TableExportFile,
)

# Dependencies
from src.models.contracts.dependencies import (
    DependencyAvailabilityRequest,
    DependencyAvailabilityResponse,
)

# Platform Admin
from src.models.contracts.platform import (
    PoolDetail,
    PoolsListResponse,
    PoolStatsResponse,
    PoolSummary,
    ProcessInfo,
    QueueItem,
    QueueStatusResponse,
    RecycleProcessRequest,
    RecycleProcessResponse,
    StuckHistoryResponse,
    StuckWorkflowStats,
)

__all__ = [
    # Re-export everything defined above
    # NOTE: Bare names like User, Organization, Role, Form, Config, ExecutionLog
    # are NOT exported here to avoid conflicts with ORM models.
    # Use *Public, *Response, *Request suffixed versions instead.
    "RetryPolicy",
    "DataProviderInputMode",
    "IntegrationType",
    "generate_entity_id",
    # Dependencies
    "DependencyAvailabilityRequest",
    "DependencyAvailabilityResponse",
    # Organizations - use OrganizationPublic for responses
    "CreateOrganizationRequest",
    "UpdateOrganizationRequest",
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationPublic",
    # Users - use UserPublic/UserResponse for responses
    "CreateUserRequest",
    "UpdateUserRequest",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPublic",
    "UserResponse",
    # Bulk user operations
    "BulkUserFailure",
    "BulkUserOperation",
    "BulkUserResponse",
    # Roles - use RolePublic for responses
    "CreateRoleRequest",
    "UpdateRoleRequest",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RolePublic",
    "RoleUserSummary",
    # User/Role assignments
    "UserPermission",
    "PermissionsData",
    "GrantPermissionsRequest",
    "UserRolesResponse",
    "UserFormsResponse",
    "RoleUsersResponse",
    "RoleFormsResponse",
    "RoleAppsResponse",
    "RoleWorkflowsResponse",
    "RoleKnowledgeResponse",
    "RoleKnowledgeEntry",
    "RoleConsumerCounts",
    "AssignUsersToRoleRequest",
    "AssignFormsToRoleRequest",
    "AssignAppsToRoleRequest",
    "AssignWorkflowsToRoleRequest",
    "AssignKnowledgeToRoleRequest",
    "KnowledgeAssignmentInput",
    "UnassignUsersFromRoleRequest",
    "UnassignFormsFromRoleRequest",
    "UnassignAgentsFromRoleRequest",
    "UnassignAppsFromRoleRequest",
    "UnassignWorkflowsFromRoleRequest",
    "UnassignKnowledgeFromRoleRequest",
    "OAuthProviderInfo",
    "AuthStatusResponse",
    "MFARequiredResponse",
    "MFASetupRequiredResponse",
    "MFAVerifyRequest",
    "LoginResponse",
    "TokenRefresh",
    "MFASetupTokenRequest",
    "MFASetupResponse",
    "MFAEnrollVerifyRequest",
    "MFAEnrollVerifyResponse",
    "OAuthLoginRequest",
    "DeviceCodeResponse",
    "DeviceTokenRequest",
    "DeviceTokenResponse",
    "DeviceTokenErrorResponse",
    "DeviceAuthorizeRequest",
    # Passkeys/WebAuthn
    "PasskeyRegistrationOptionsRequest",
    "PasskeyRegistrationOptionsResponse",
    "PasskeyRegistrationVerifyRequest",
    "PasskeyRegistrationVerifyResponse",
    "PasskeyAuthOptionsRequest",
    "PasskeyAuthOptionsResponse",
    "PasskeyAuthVerifyRequest",
    "PasskeyPublic",
    "PasskeyListResponse",
    "PasskeyDeleteResponse",
    # Forms - use FormPublic for responses
    "FormFieldValidation",
    "DataProviderInputConfig",
    "FormSchema",
    "CreateFormRequest",
    "UpdateFormRequest",
    "FormConfirmationResponse",
    "FormExecutionResponse",
    "FormFieldOptionsRequest",
    "FormFieldOptionsResponse",
    "FormStartupResponse",
    "FormSubmissionRequest",
    "FormSubmissionResponse",
    "FormCreate",
    "FormUpdate",
    "FormPublic",
    "FormCaptchaChallenge",
    "FormRuntimeDefinition",
    "FormPublicationPublic",
    "FormPublicationReview",
    "FormPublicationUpdate",
    # Agents & Chat - use AgentPublic for responses
    "AgentCreate",
    "AgentUpdate",
    "AgentPublic",
    "AgentSummary",
    "ConversationCreate",
    "ConversationPublic",
    "ConversationSummary",
    "MessagePublic",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamChunk",
    "ToolCall",
    "ToolResult",
    "AssignAgentsToRoleRequest",
    "RoleAgentsResponse",
    # Executions
    "ExecutionBase",
    "ExecutionLogPublic",
    "AIUsagePublicSimple",
    "AIUsageTotalsSimple",
    "WorkflowExecution",
    "WorkflowExecutionRequest",
    "WorkflowExecutionResponse",
    "ExecutionsListResponse",
    "StuckExecutionsResponse",
    "CleanupTriggeredResponse",
    "ExecutionCreate",
    "ExecutionUpdate",
    "ExecutionPublic",
    # Audit log
    "AuditLogActor",
    "AuditLogEntry",
    "AuditLogListResponse",
    # Config - use ConfigResponse or ConfigPublic for responses
    "SetConfigRequest",
    "UpdateConfigRequest",
    "ConfigBase",
    "ConfigCreate",
    "ConfigUpdate",
    "ConfigPublic",
    "ConfigResponse",
    "IntegrationConfig",
    "SetIntegrationConfigRequest",
    "SecretListResponse",
    "SecretCreateRequest",
    "SecretUpdateRequest",
    "SecretResponse",
    "SecretBase",
    "SecretCreate",
    "SecretUpdate",
    "SecretPublic",
    "HealthCheck",
    "BasicHealthResponse",
    "GeneralHealthResponse",
    "ExecutionStats",
    "RecentFailure",
    "ROISnapshot",
    "DashboardMetricsResponse",
    "ExecutionTimeSeriesBucket",
    "ExecutionTimeSeriesResponse",
    "PlatformMetricsResponse",
    "DailyMetricsEntry",
    "DailyMetricsResponse",
    "OrganizationMetricsSummary",
    "OrganizationMetricsResponse",
    "ResourceMetricsEntry",
    "ResourceMetricsResponse",
    "WorkflowMetricsSummary",
    "WorkflowMetricsResponse",
    "OAuthFlowType",
    "OAuthStatus",
    "CreateOAuthConnectionRequest",
    "UpdateOAuthConnectionRequest",
    "OAuthConnectionSummary",
    "OAuthConnectionDetail",
    "OAuthConnection",
    "OAuthCredentials",
    "OAuthCredentialsModel",
    "OAuthCredentialsResponse",
    "EntityIdPickerCandidate",
    "OAuthCallbackRequest",
    "OAuthCallbackResponse",
    "OAuthProviderBase",
    "OAuthProviderCreate",
    "OAuthProviderUpdate",
    "OAuthProviderPublic",
    "FileUploadRequest",
    "FileUploadResponse",
    "UploadedFileMetadata",
    "WorkflowKey",
    "WorkflowKeyCreateRequest",
    "WorkflowKeyResponse",
    "AsyncExecution",
    "AsyncExecutionStatus",
    "CronValidationRequest",
    "CronValidationResponse",
    "BrandingSettings",
    "BrandingTerm",
    "BrandingTerminology",
    "BrandingUpdateRequest",
    "FileType",
    "FileMetadata",
    "FileContentRequest",
    "FileContentResponse",
    "FileConflictResponse",
    "FileStatResponse",
    "FileDiagnostic",
    "WorkflowIdConflict",
    "AffectedEntity",
    "PendingDeactivation",
    "AvailableReplacement",
    "WorkflowDeactivationConflict",
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "ScriptExecutionRequest",
    "ScriptExecutionResponse",
    "InstallPackageRequest",
    "PackageInstallResponse",
    "InstalledPackage",
    "InstalledPackagesResponse",
    "PackageUpdate",
    "PackageUpdatesResponse",
    "GitFileStatus",
    "FileChange",
    "ConflictInfo",
    "ValidateTokenRequest",
    "GitHubConfigRequest",
    "GitHubConfigResponse",
    "GitHubRepoInfo",
    "GitHubReposResponse",
    "GitHubBranchInfo",
    "WorkspaceAnalysisResponse",
    "CreateRepoRequest",
    "CreateRepoResponse",
    "GitHubBranchesResponse",
    "CommitAndPushRequest",
    "CommitAndPushResponse",
    "FetchFromGitHubResponse",
    "GitHubSetupResponse",
    "GitRefreshStatusResponse",
    "RepoStatusResponse",
    "CommitHistoryResponse",
    "CommitInfo",
    "DetectedRepoInfo",
    "GitHubConfigEntity",
    # Git sync models
    "PreflightIssue",
    "PreflightResult",
    "WorkflowReference",
    "OrphanInfo",
    # Orphan management models
    "OrphanedWorkflowInfo",
    "OrphanedWorkflowsResponse",
    "CompatibleReplacement",
    "CompatibleReplacementsResponse",
    "ReplaceWorkflowRequest",
    "ReplaceWorkflowResponse",
    "RemapWorkflowRequest",
    "RemapWorkflowResponse",
    "RecreateFileResponse",
    "DeactivateWorkflowResponse",
    # Desktop-style git sync models
    "GitJobResponse",
    "GitOpRequest",
    "SyncRequest",
    "CommitRequest",
    "ResolveRequest",
    "DiffRequest",
    "DiscardRequest",
    "DiscardResult",
    "ConfirmDeletionsRequest",
    "ConfirmDeletionsResult",
    "ChangedFile",
    "MergeConflict",
    "FetchResult",
    "WorkingTreeStatus",
    "CommitResult",
    "PullResult",
    "PushResult",
    "ResolveResult",
    "SyncResult",
    "AbortMergeResult",
    "DiffResult",
    "SyncExecuteRequest",
    # CLI Models
    "CLIFileReadRequest",
    "CLIFileWriteRequest",
    "CLIFileListRequest",
    "CLIFileDeleteRequest",
    "CLIConfigGetRequest",
    "CLIConfigSetRequest",
    "CLIConfigListRequest",
    "CLIConfigDeleteRequest",
    "CLIConfigValue",
    # CLI Session Models
    "CLIRegisteredWorkflow",
    "CLISessionRegisterRequest",
    "CLISessionResponse",
    "CLISessionListResponse",
    "CLISessionContinueRequest",
    "CLISessionContinueResponse",
    "CLISessionPendingResponse",
    "CLISessionLogRequest",
    "CLISessionResultRequest",
    "CLISessionExecutionSummary",
    "ErrorResponse",
    "WorkflowParameter",
    "WorkflowMetadata",
    "DataProviderMetadata",
    "MetadataResponse",
    "FormDiscoveryMetadata",
    "RegisterWorkflowRequest",
    "RegisterWorkflowResponse",
    "ValidationIssue",
    "WorkflowUpdateRequest",
    "WorkflowValidationRequest",
    "WorkflowValidationResponse",
    "EntityUsage",
    "WorkflowUsageStats",
    "WorkflowRolesResponse",
    "AssignRolesToWorkflowRequest",
    "DeleteWorkflowRequest",
    "DataProviderRequest",
    "DataProviderOption",
    "DataProviderResponse",
    # Notifications
    "NotificationCategory",
    "NotificationStatus",
    "NotificationCreate",
    "NotificationUpdate",
    "NotificationPublic",
    "NotificationListResponse",
    "JobDispatchResponse",
    "UploadLockInfo",
    # Profile
    "ProfileUpdate",
    "PasswordChange",
    "ProfileResponse",
    # Memory
    "MemoryDeleteResponse",
    "MemoryEntryList",
    "MemoryEntryPublic",
    "MemoryPlatformSettings",
    "MemoryPlatformSettingsUpdate",
    "MemorySaveRequest",
    "MemorySearchRequest",
    "MemorySearchResponse",
    "MemorySearchResult",
    "MemoryUserSettings",
    "MemoryUserSettingsUpdate",
    "RequiredInstructionsResponse",
    "RequiredInstructionsSettings",
    # External MCP client
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPServerSummary",
    "MCPServerPublic",
    "MCPConnectionCreate",
    "MCPConnectionUpdate",
    "MCPConnectionSummary",
    "MCPConnectionPublic",
    "MCPConnectionToolCreate",
    "MCPConnectionToolUpdate",
    "MCPConnectionToolPublic",
    "UserMCPCredentialCreate",
    "UserMCPCredentialPublic",
    # Integrations
    "ConfigItemType",
    "ConfigSchemaItem",
    "IntegrationCreate",
    "IntegrationUpdate",
    "IntegrationResponse",
    "IntegrationDetailResponse",
    "IntegrationListResponse",
    "IntegrationMappingCreate",
    "IntegrationMappingUpdate",
    "IntegrationMappingBatchItem",
    "IntegrationMappingBatchRequest",
    "IntegrationMappingBatchResponse",
    "IntegrationMappingResponse",
    "IntegrationMappingListResponse",
    "EntityIdSourceUpdateRequest",
    "MappingAuthorizeRequest",
    "MappingAuthorizeResponse",
    "IntegrationData",
    "IntegrationTestRequest",
    "IntegrationTestResponse",
    "OAuthConfigSummary",
    # Decorator Properties
    "DecoratorType",
    "DecoratorInfo",
    "DecoratorPropertiesResponse",
    "UpdatePropertiesRequest",
    "UpdatePropertiesResponse",
    # Maintenance
    "CleanupOrphanedResponse",
    "DocsIndexResponse",
    "MaintenanceStatus",
    "OrphanedEntity",
    "PreflightIssueResponse",
    "PreflightResponse",
    "ReimportJobResponse",
    # ROI
    "ROISettingsRequest",
    "ROISettingsResponse",
    "ROISummaryResponse",
    "WorkflowROIEntry",
    "ROIByWorkflowResponse",
    "OrganizationROIEntry",
    "ROIByOrganizationResponse",
    "ROITrendEntry",
    "ROITrendsResponse",
    # AI Usage
    "AIModelPricingBase",
    "AIModelPricingCreate",
    "AIModelPricingUpdate",
    "AIModelPricingPublic",
    "AIModelPricingListItem",
    "AIModelPricingListResponse",
    "AIUsageBase",
    "AIUsagePublic",
    "AIUsageTotals",
    "AIUsageByModel",
    "AIUsageSummaryResponse",
    "UsageReportSummary",
    "UsageTrend",
    "WorkflowUsage",
    "ConversationUsage",
    "AgentUsage",
    "OrganizationUsage",
    "KnowledgeStorageUsage",
    "KnowledgeStorageTrend",
    "UsageReportResponse",
    # SDK Response Models
    "ConfigData",
    "IntegrationData",
    "SDKOAuthCredentials",
    # Applications (App Builder)
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationPublic",
    "ApplicationListResponse",
    "ApplicationDefinition",
    "ApplicationDraftSave",
    "ApplicationPublishRequest",
    "ApplicationRollbackRequest",
    "VersionHistoryEntry",
    "VersionHistoryResponse",
    # App Files
    "AppFileCreate",
    "AppFileUpdate",
    "AppFileResponse",
    "AppFileListResponse",
    # Durable scheduler-owned platform jobs
    "PlatformJobAccepted",
    "PlatformJobCancelResponse",
    "PlatformJobError",
    "PlatformJobListResponse",
    "PlatformJobProgress",
    "PlatformJobPublic",
    "PlatformJobStatus",
    "SchedulerCapacityStatus",
    "SchedulerDiagnosticsResponse",
    "SchedulerLeaderStatus",
    "SchedulerReplicaStatus",
    "SchedulerTaskRunStatus",
    "SchedulerTaskStatus",
    "SystemDiagnosticLogPublic",
    # Platform Admin
    "PoolDetail",
    "PoolsListResponse",
    "PoolStatsResponse",
    "PoolSummary",
    "ProcessInfo",
    "QueueItem",
    "QueueStatusResponse",
    "RecycleProcessRequest",
    "RecycleProcessResponse",
    "StuckHistoryResponse",
    "StuckWorkflowStats",
    # File Operations (CLI push/pull)
    "FilePullRequest",
    "FilePullResponse",
    "WatchSessionRequest",
    # Export/Import
    "ExportMetadata",
    "KnowledgeExportFile",
    "TableExportFile",
    "ConfigExportFile",
    "IntegrationExportFile",
    "BulkExportRequest",
    "ImportResult",
    "ImportResultItem",
    # AI Model Settings
    "AIConnectionTestResponse",
    "AIModelAssignmentKey",
    "AIModelAssignmentResponse",
    "AIModelAssignmentUpdate",
    "AIModelProfileCreate",
    "AIModelProfileMergeRequest",
    "AIModelProfileMergeResponse",
    "AIModelProfileResponse",
    "AIModelProfileUpdate",
    "AIModelsResponse",
    "AIProviderConnectionCreate",
    "AIProviderConnectionResponse",
    "AIProviderConnectionSummary",
    "AIProviderConnectionUpdate",
    "AIProviderKind",
]
