name: Build and Release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

# Only run in upstream repo to prevent forks from creating releases
# Forks should use their own deployment workflows

permissions:
    contents: write # Required to create releases

jobs:
    build-api:
        runs-on: ubuntu-latest
        name: Build API Package
        # Only run in upstream repo, not forks
        if: github.event.repository.fork == false

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Build API package
              run: |
                  python -m pip install -q --upgrade pip
                  pip install -q -r requirements.txt --target=".python_packages/lib/site-packages"

                  # Create zip excluding unnecessary files
                  zip -q -r api.zip . \
                    -x "*.pyc" \
                    -x "*__pycache__*" \
                    -x "tests/*" \
                    -x ".git/*" \
                    -x ".venv/*" \
                    -x ".devcontainer/*" \
                    -x ".github/*"

            - name: Upload API artifact
              uses: actions/upload-artifact@v4
              with:
                  name: api-package
                  path: api.zip
                  retention-days: 90

    create-release:
        needs: [build-api]
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

        steps:
            - name: Download API artifact
              uses: actions/download-artifact@v4
              with:
                  name: api-package

            - name: Upload versioned package to Azure Blob Storage
              uses: bacongobbler/azure-blob-storage-upload@main
              with:
                  source_dir: .
                  container_name: ${{ secrets.RELEASES_CONTAINER_NAME }}
                  connection_string: ${{ secrets.RELEASES_STORAGE_CONNECTION_STRING }}
                  extra_args: '--pattern api.zip --destination-path api/${{ github.ref_name }}.zip'
                  overwrite: 'true'

            - name: Upload latest.zip to Azure Blob Storage
              uses: bacongobbler/azure-blob-storage-upload@main
              with:
                  source_dir: .
                  container_name: ${{ secrets.RELEASES_CONTAINER_NAME }}
                  connection_string: ${{ secrets.RELEASES_STORAGE_CONNECTION_STRING }}
                  extra_args: '--pattern api.zip --destination-path api/latest.zip'
                  overwrite: 'true'

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      api.zip
                  body: |
                      ## Bifrost Integrations Release

                      ### Installation

                      **One-Click Deploy:**
                      [![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjackmusick%2Fbifrost-api%2Fmain%2Fdeployment%2Fazuredeploy.json)

                      The API package is automatically deployed from Azure Blob Storage:
                      - **Latest**: `https://${{ secrets.RELEASES_STORAGE_ACCOUNT }}.blob.core.windows.net/${{ secrets.RELEASES_CONTAINER_NAME }}/api/latest.zip`

                      **Manual Zip Deploy:**
                      ```bash
                      # Deploy API Function App
                      az functionapp deployment source config-zip \
                        --resource-group <rg-name> \
                        --name <api-app-name> \
                        --src api.zip
                      ```
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
