name: Deploy Static Web App

on:
    push:
        branches:
            - main
        paths:
            - "client/**"
            - ".github/workflows/deploy-static-web-app.yml"
    workflow_dispatch:

jobs:
    build_and_deploy_job:
        # Only run in forks (users deploy to their own Azure Static Web App)
        if: github.event.repository.fork == true
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"
                  app_location: "/client"
                  api_location: ""
                  output_location: "dist"
