name: Protect Engine Directory

"on":
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-engine-protection:
    name: Verify Engine Directory Protection
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            workflows/engine/**

      - name: Check if engine was modified
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Allow upstream-sync bot and github-actions bot
          if [[ "${{ github.actor }}" == "upstream-sync[bot]" ]] || [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
            echo "✓ Authorized bot detected: ${{ github.actor }}"
            echo "Bot is allowed to modify engine directory"
            exit 0
          fi

          # Block all other actors from modifying engine
          echo "::error::Unauthorized modification of /workflows/engine directory detected"
          echo "::error::Only upstream-sync[bot] and github-actions[bot] can modify engine code"
          echo "::error::Modified files: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo ""
          echo "The /workflows/engine directory contains core platform code and should not be"
          echo "modified directly. Please only modify files in /workflows/workspace."
          echo ""
          echo "If you need to modify engine code, please:"
          echo "  1. Submit an issue describing the needed change"
          echo "  2. Wait for platform maintainers to review and implement"
          echo "  3. Your fork will receive the change via upstream sync"
          exit 1

      - name: Success
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo "✓ No engine directory modifications detected"
          echo "Workspace changes are allowed and encouraged!"
