name: Protect Engine Directory

# Trigger on pushes and pull requests to main/develop branches
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate-engine-protection:
    name: Validate Engine Protection
    runs-on: ubuntu-latest
    timeout-minutes: 2  # T020: Fast failure (2 minute timeout)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # T017: Full history for accurate change detection

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          # T017: Detect changes in /engine/** path
          files: |
            workflows/engine/**

      - name: Check for engine modifications
        id: check-engine
        run: |
          # T018: Bot detection logic - Allow authorized bots
          ACTOR="${{ github.actor }}"

          if [[ "$ACTOR" == "upstream-sync[bot]" ]] || [[ "$ACTOR" == "github-actions[bot]" ]]; then
            echo "✓ Authorized bot detected: $ACTOR"
            echo "bot_authorized=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check if any engine files were modified
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Block engine modifications
        if: steps.check-engine.outputs.changed == 'true' && steps.check-engine.outputs.bot_authorized != 'true'
        run: |
          # T019: Error message formatting with ::error GitHub Actions command
          echo "::error title=Protected Directory Violation::Modifications to /engine/* are not allowed from developer commits."
          echo "::error::The /engine directory is synchronized from the upstream repository only."
          echo "::error::Developers should only modify files in /workspace directory."
          echo ""
          echo "Changed files in protected /engine directory:"
          echo "${{ steps.check-engine.outputs.files }}" | tr ' ' '\n' | while read file; do
            echo "  - $file"
          done
          echo ""
          echo "::error::If you believe this is a mistake, please contact the platform team."
          exit 1

      - name: Report success
        if: steps.check-engine.outputs.changed != 'true' || steps.check-engine.outputs.bot_authorized == 'true'
        run: |
          if [[ "${{ steps.check-engine.outputs.bot_authorized }}" == "true" ]]; then
            echo "✓ Engine protection: Authorized bot modification allowed"
          else
            echo "✓ Engine protection: No engine files modified"
          fi
